module Activerecord
  module Enhanced
    module Sqlite3
      module Adapter
        VERSION: String
        # See the writing guide of rbs: https://github.com/ruby/rbs#guides
      end
    end
  end
end
